crm/accounts/urls.py
from django.urls import path

from . import views
app_name = 'accounts'
urlpatterns = [
    path('employees/', views.EmployeeListView.as_view(), name="employees"),
    path('login/', views.user_login, name='user_login'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('profile', views.UserProfileDetailView.as_view(), name='profile'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path('profile/password/', views.change_password, name='change_password'),
    path('profile/profile_pic_default',
         views.delete_profile_pic, name='delete_profile_pic'
         ),
    path('register/', views.register, name='register'),
    path('first_login/<str:string>/', views.first_login, name='first_login'),
    path('set_password/', views.set_password, name='set_password'),
]

crm/calendary/urls.py
from django.urls import path
from . import views
app_name = 'calendary'
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('<int:year>/<int:month>/',
        views.DayListView.as_view(), name='calendary'),
    path('<int:pk>/addevent/',views.post_devent,name='post_devent'),
    path('event/<slug:slug>',views.DeventDetailView.as_view(),name='devent'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/crm/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('suggestions/',include('suggestions.urls',namespace="suggestions")),
    path('calendar/',include('calendary.urls',namespace="calendar")),
    path('',include('news.urls',namespace="news")),
    path('polls/',include('polls.urls',namespace="polls")),
    path('accounts/api/',include('accounts.api.urls')),
    path('calendar/api/',include('calendary.api.urls')),
    path('news/api/',include('news.api.urls')),
    path('suggestions/api/',include('suggestions.api.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/news/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from news import views
app_name = 'news'

urlpatterns = [
    path('', views.NewsListView.as_view(), name="news_list"),
    path('news/<int:pk>/', views.NewsDetailView.as_view(), name="newsdetail"),
    path('news/unpublished/',
         views.UnpublishedNewsListView.as_view(), name="unpublished"),
    path('knowledge/', views.KnowledgeCategoryListView.as_view(), name="knowledge"),
    path('knowledge/<int:pk>', views.KnowledgeCategoryDetailView.as_view(),
         name="knowledgedetail"),
    path('upload/news', views.post_news, name="post_news"),
    path('upload/doc', views.post_document, name="createdoc"),
    path('upload/file', views.post_file, name="createfile"),
    path('upload/question', views.post_question, name="createquestion"),
    path('upload/userquestion', views.post_userquestion, name="createuserquestion"),
    path('upload/<int:pk>/updatequestion',
         views.UpdateDocQuestionView.as_view(), name="answerfaq"),
    path('upload/<int:pk>/updatenews',
         views.UnpublishedNewsUpdateView.as_view(), name="updatenews"),
    path('news/<int:pk>/publish/', views.publish_news, name="publish_news"),
    path('flagtoggle/', views.flagtoggle, name="flagtoggle"),
    path('markall/', views.markall, name="markall"),
    path('docs/<int:pk>/', views.DocDetailView.as_view(), name="docdetail"),
    path('faq/', views.QuestionListView.as_view(), name="faq"),
    path('faq/pending/', views.UnansweredQuestionListView.as_view(),
         name="pending_faq"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/polls/urls.py
from django.urls import path
from . import views
app_name = 'polls'
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # path('employees/',views.EmployeeListView.as_view(),name="employees"),
    path('',views.PollListView.as_view(),name="poll_list"),
    path('unpublished/',views.UnpublishedPollListView.as_view(),name="unpublishedpolllist"),
    path('<int:pk>/',views.create_poll_answer,name="create_poll_answer"),
    path('add/',views.post_Poll,name="pollform"),
    path('add/<int:pk>/',views.create_poll_question,name="create_poll_question"),
    path('publish/<int:pk>/',views.publishpoll,name="publishpoll"),
    path('submitions/',views.PollListAnswerView.as_view(),name="poll_submitions"),
    path('submitions/<int:pk>',views.PollAnswerDetailView.as_view(),name="detailanswers")

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load groupfilter %}
{% load i18n %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>intranet</title>
    <script
  src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/script.js' %}" charset="utf-8"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
  <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
<style media="screen">
{% block extra_css %}{% endblock %}

</style>
  </head>
  <body>

    <!-- covers that collapse dropdowns on click -->
     <div class="cover" onclick="toggleDropdown1()">
     </div>
     <div class="cover2" onclick="toggleDropdown2()">
     </div>

     <div class="all-content-wrapper">


        <div class="top-bar">
           <div class="top-bar__logo ">
              <span>intranet</span>
           </div>
           <div onclick="collapseNavigation()" class="top-bar__item top-bar__item--first">
              <i class="fa fa-bars top-bar_icon"></i>
           </div>

           <div onclick="toggleDropdown1()" id="dropdown-trigger" class=" top-bar__item">
              <span><i class="fas fa-globe top-bar_icon"></i></span>
           </div>



           <div id="dropdown" class="dropdown dropdown--notif">
              <div class="dropdown__header">
                 <span>Notifications</span><span data-href="{% url "news:markall" %}" class="smol markall">Mark all as read</span>
              </div>
              <div class="dropdown__body">
                 {% for each in user.notificationreadflag_set.all|in_category|slice:":7" %}
                 <a href="{% url 'news:newsdetail' pk=each.notification.news.pk %}">
                    <div  data-href="{% url 'news:flagtoggle' %}" data-pk="{{each.notification.news.pk}}" class="dropdown_notification primary-hover">
                       <div class="dropdown_notification__header">
                          {{each.notification.title}}
                       </div>
                       <div class="dropdown_notification__body">
                          {{each.notification.body}}
                       </div>
                    </div>
                 </a>
                 {% empty %}
                 <span class="nonews">  You dont have any new notifications</span>
                 {% endfor %}
              </div>
              <div class="dropdown__footer">
              </div>
           </div>




           <div onclick="toggleDropdown2()" id="dropdown-trigger-2" class="top-bar__item">
              <span>      <i class="fas fa-user-alt"></i> {{user.userprofile.name}}</span>
              <div  id="dropdown2" class="dropdown dropdown--prof">
                 <div class="dropdown__body">
                    <a href="{% url 'accounts:profile' %}">
                       <div class="dropdown_notification-last secondary-hover">Profile</div>
                    </a>
                    <a href="{% url 'accounts:user_logout' %}"><div class="dropdown_notification-last secondary-hover">
                      Logout</div></a>
                 </div>
              </div>
           </div>
        </div>





        <div class="undercontent">
           <div class="sidebar">
                 <nav>
                    <div class="nav__title">
                       navigation
                    </div>
                    {% now "n" as current %}
                    {% now "Y" as currentyear %}
                    <a href="{% url 'news:news_list' %}" class="nav__link" name="Home"><i class="fas fa-home"></i> <span class="navlink">Home</span></a>
                    <a href="{% url 'news:knowledge' %}" class="nav__link" name="Knowledge"><i class="fas fa-paperclip"></i> <span class="navlink">Knowledge</span></a>
                    <a href="{% url 'news:faq' %}" class="nav__link" name="faq"><i class="fas fa-paperclip"></i> <span class="navlink">Q&A</span></a>
                    <a href="{% url 'calendary:calendary' month=current year=currentyear %}" class="nav__link" name="Calendar"><i class="fas fa-calendar-alt"></i> <span class="navlink">Calendar</span></a>
                    <a href="{% url 'suggestions:postlist' %}" class="nav__link" name="Message Board"><i class="far fa-comment-alt"></i> <span class="navlink">Message Board</span></a>
                    <a href="{% url 'accounts:employees' %}" class="nav__link" name="Contact List"><i class="fas fa-phone"></i> <span class="navlink">Contact List</span></a>
                    <a href="{% url 'polls:poll_list' %}" class="nav__link" name="Polls"><i class="fas fa-poll"></i> <span class="navlink">Surveys</span></a>
                 </nav>

           </div>



           <div class="right-column">
              <div class="content-block">
                 {% block body_block %}
                 {% endblock %}
              </div>
           </div>
        </div>
     </div>
  </body>

</html>

crm/templates/basenew.html
<!DOCTYPE html>
{% load static %}
{% load groupfilter %}
{% load i18n %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>intranet</title>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'css/input.css' %}">
  <script src="{% static 'js/script.js' %}" charset="utf-8"></script>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
  <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
  <style media="screen">
    {
      % block extra_css %
    }

      {
      % endblock %
    }
  </style>
</head>

<body>

  <!-- covers that collapse dropdowns on click -->
   <div class="cover" onclick="toggleDropdown1()">
   </div>
   <div class="cover2" onclick="toggleDropdown2()">
   </div>

   <div class="all-content-wrapper">


      <nav class="top-bar">
         <div class="top-bar__logo ">
            <span>intranet</span>
         </div>
         <div onclick="collapseNavigation()" id="top-bar__collapse" class="top-bar__item">
            <i class="fa fa-bars top-bar_icon"></i>
         </div>

         <div onclick="toggleDropdown1()" id="dropdown-trigger" class="top-bar__item">
            <span><i class="fas fa-globe top-bar_icon"></i></span>
         </div>




      <div id="dropdown" class=" dropdown dropdown--notif">
        <header>
          <span>Notifications</span> <span data-href="{% url "news:markall" %}" class="smol markall">Mark all as read</span>
        </header>
        <div class="dropdown__body">
          {% for each in user.notificationreadflag_set.all|in_category|slice:":7" %}
          <a href="{% url 'news:newsdetail' pk=each.notification.news.pk %}">
            <div data-href="{% url 'news:flagtoggle' %}" data-pk="{{each.notification.news.pk}}" class="dropdown_notification primary-hover">
              <div class="dropdown_notification__header">
                {{each.notification.title}}
              </div>
              <div class="dropdown_notification__body">
                {{each.notification.body}}
              </div>
            </div>
          </a>
          {% empty %}
          <span class="nonews"> You dont have any new notifications</span>
          {% endfor %}
        </div>
        <footer>
        </footer>
      </div>




      <div onclick="toggleDropdown2()" id="dropdown-trigger-2" class="top-bar__item">
        <span> <i class="fas fa-user-alt"></i> {{user.userprofile.name}}</span>
        <div id="dropdown2" class="dropdown dropdown--prof">
          <div class="dropdown__body">
            <a href="{% url 'accounts:profile' %}">
              <div class="dropdown_notification-last secondary-hover">Profile</div>
            </a>
            <a href="{% url 'accounts:user_logout' %}">
              <div class="dropdown_notification-last secondary-hover">
                Logout</div>
            </a>
          </div>
        </div>
      </div>
    </nav>





    <div class="undercontent">
      <div class="sidebar">
        <nav>
          <div class="nav__title">
            navigation
          </div>
          {% now "n" as current %}
          {% now "Y" as currentyear %}
          <a href="{% url 'news:news_list' %}" class="nav__link" name="Home"><i class="fas fa-home"></i> <span class="navlink">Home</span></a>
          <a href="{% url 'news:knowledge' %}" class="nav__link" name="Knowledge"><i class="fas fa-paperclip"></i> <span class="navlink">Knowledge</span></a>
          <a href="{% url 'news:faq' %}" class="nav__link" name="faq"><i class="fas fa-paperclip"></i> <span class="navlink">Q&A</span></a>
          <a href="{% url 'calendary:calendary' month=current year=currentyear %}" class="nav__link" name="Calendar"><i class="fas fa-calendar-alt"></i> <span class="navlink">Calendar</span></a>
          <a href="{% url 'suggestions:postlist' %}" class="nav__link" name="Message Board"><i class="far fa-comment-alt"></i> <span class="navlink">Message Board</span></a>
          <a href="{% url 'accounts:employees' %}" class="nav__link" name="Contact List"><i class="fas fa-phone"></i> <span class="navlink">Contact List</span></a>
          <a href="{% url 'polls:poll_list' %}" class="nav__link" name="Polls"><i class="fas fa-poll"></i> <span class="navlink">Surveys</span></a>
        </nav>

      </div>



      <div class="right-column">
        <div class="content-block">
          {% block body_block %}
          {% endblock %}
        </div>
      </div>
    </div>
  </div>
</body>

</html>