crm/accounts/api/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework_jwt.views import refresh_jwt_token, obtain_jwt_token
from .views import *
urlpatterns = [
    path('', AuthAPIView.as_view()),
    path('register/', RegisterAPIView.as_view()),
    path('jwt/', obtain_jwt_token),
    path('jwt/refresh/', refresh_jwt_token),
    path('list/', UserProfileListAPIView.as_view()),
    path('profile/', UserProfileDetailAPIView.as_view()),
]

crm/accounts/urls.py
from django.urls import path

from . import views
app_name = 'accounts'
urlpatterns = [
    path('employees/', views.EmployeeListView.as_view(), name="employees"),
    path('login/', views.user_login, name='user_login'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('profile', views.UserProfileDetailView.as_view(), name='profile'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path('profile/password/', views.change_password, name='change_password'),
    path('profile/profile_pic_default',
         views.delete_profile_pic, name='delete_profile_pic'
         ),
    path('register/', views.register, name='register'),
    path('first_login/<str:string>/', views.first_login, name='first_login'),
    path('set_password/', views.set_password, name='set_password'),
]

crm/crm/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('suggestions/',include('suggestions.urls',namespace="suggestions")),
    path('calendar/',include('calendary.urls',namespace="calendar")),
    path('',include('news.urls',namespace="news")),
    path('polls/',include('polls.urls',namespace="polls")),
    path('accounts/api/',include('accounts.api.urls')),
    path('calendar/api/',include('calendary.api.urls')),
    path('news/api/',include('news.api.urls')),
    path('suggestions/api/',include('suggestions.api.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/news/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from news import views
app_name = 'news'

urlpatterns = [
    path('', views.NewsListView.as_view(), name="news_list"),
    path('news/<int:pk>/', views.NewsDetailView.as_view(), name="newsdetail"),
    path('news/unpublished/',
         views.UnpublishedNewsListView.as_view(), name="unpublished"),
    path('knowledge/', views.KnowledgeCategoryListView.as_view(), name="knowledge"),
    path('knowledge/<int:pk>', views.KnowledgeCategoryDetailView.as_view(),
         name="knowledgedetail"),
    path('upload/news', views.post_news, name="post_news"),
    path('upload/doc', views.post_document, name="createdoc"),
    path('upload/file', views.post_file, name="createfile"),
    path('upload/question', views.post_question, name="createquestion"),
    path('upload/userquestion', views.post_userquestion, name="createuserquestion"),
    path('upload/<int:pk>/updatequestion',
         views.UpdateDocQuestionView.as_view(), name="answerfaq"),
    path('upload/<int:pk>/updatenews',
         views.UnpublishedNewsUpdateView.as_view(), name="updatenews"),
    path('news/<int:pk>/publish/', views.publish_news, name="publish_news"),
    path('flagtoggle/', views.flagtoggle, name="flagtoggle"),
    path('markall/', views.markall, name="markall"),
    path('docs/<int:pk>/', views.DocDetailView.as_view(), name="docdetail"),
    path('faq/', views.QuestionListView.as_view(), name="faq"),
    path('faq/pending/', views.UnansweredQuestionListView.as_view(),
         name="pending_faq"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/accounts/models.py
import random
import string
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from PIL import Image
import os
from django.conf import settings
from accounts.choices.choices import *

class AvatarManager(models.Manager):
    def resize_file(self, file):
        name, ext = os.path.splitext(file.name)
        print(name + "  " + ext)
        format_ext_dict = {'.jpg': 'JPEG', '.png': 'PNG', '.gif': 'GIF'}
        img_format = format_ext_dict[ext]
        im = Image.open(file)
        im.thumbnail((128, 128), Image.ANTIALIAS)
        save_name = settings.MEDIA_DIR + '/profile_pics/' + name + ext
        im.save(fp=save_name, format=img_format)
        print(save_name)
        return save_name


class UserProfile(models.Model):

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="userprofile"
    )

    profile_pic = models.ImageField(
        upload_to='profile_pics',
        default='profile_pics/default-profile.png',
        blank=True
    )

    name = models.CharField(max_length=30)
    telephone = models.PositiveIntegerField()
    email = models.EmailField(max_length=50)
    date_of_employement = models.DateField(default=timezone.now)
    employee_id = models.PositiveIntegerField()
    position = models.CharField(max_length=40, default="trainee")
    objects = AvatarManager()
    first_login_string = models.CharField(max_length=30, null=True)
    is_active = models.BooleanField(default=False)
    departament = models.CharField(
        max_length=3,
        choices=DEPARTAMENTS,
        default='non'
    )

    location = models.CharField(
        max_length=3,
        choices=COMPANY_LOCATIONS,
        default='non'
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        profiles = UserProfile.objects.order_by('-employee_id')
        highest_id = profiles[0].employee_id
        self.employee_id = highest_id + 1
        self.first_login_string = ''.join(random.choices( \
            string.ascii_letters + string.digits, k=15))
        super(UserProfile, self).save(*args, **kwargs)


    class Meta:
        ordering = ['employee_id']

    def set_default_profile_pic(self):
        if self.profile_pic != "profile_pics/default-profile.png":
            try:
                if os.path.isfile(self.profile_pic.path):
                    os.remove(self.profile_pic.path)
            except:
                pass
            self.profile_pic = "profile_pics/default-profile.png"
            self.save()


    def change_profile_pic(self,file):
        prev_pic = self.profile_pic
        image = UserProfile.objects.resize_file(file)
        self.profile_pic = image
        self.save()
        try:
            if (prev_pic != "profile_pics/default-profile.png" and
                prev_pic != self.profile_pic):
                if os.path.isfile(prev_pic.path):
                    os.remove(prev_pic.path)
        except:
            pass

crm/accounts/forms.py
from django import forms
from .models import UserProfile
from django.forms import ClearableFileInput
from django.contrib.auth.models import User
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic']

class CreateProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['name',
                'telephone',
                'position',
                'departament',
                'location',]

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','email']

crm/accounts/api/views.py
from django.contrib.auth import authenticate, get_user_model
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import generics, permissions
from rest_framework_jwt.settings import api_settings
from django.db.models import Q
from .serializers import UserRegisterSerializer, UserProfileSerializer, ChangePasswordSerializer
from rest_framework import generics, mixins, permissions
from rest_framework.authentication import SessionAuthentication
from accounts.models import UserProfile
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from rest_framework import status
User = get_user_model()
jwt_payload_handler = api_settings.JWT_PAYLOAD_HANDLER
jwt_encode_handler = api_settings.JWT_ENCODE_HANDLER
jwt_response_payload_handler = api_settings.JWT_RESPONSE_PAYLOAD_HANDLER


class RegisterAPIView(generics.CreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserRegisterSerializer
    permission_classes = [permissions.AllowAny]

    def get_serializer_context(self, *args, **kwargs):
        return {'request': self.request}


class UserProfileListAPIView(
        generics.ListAPIView):

    permission_classes = [permissions.IsAuthenticated]
    serializer_class = UserProfileSerializer
    passed_id = None

    def get_queryset(self):
        object_list = UserProfile.objects.all()
        if self.request.GET.get('q') != None:
            query = self.request.GET.get('q')

            object_list = UserProfile.objects.all().filter(
                Q(name__icontains=query) | Q(email__icontains=query)
                | Q(departament__icontains=query) | Q(location__icontains=query)
                | Q(position__icontains=query) | Q(telephone__icontains=query)
            )

        return object_list


class UserProfileDetailAPIView(mixins.UpdateModelMixin,
                               generics.RetrieveAPIView):
    permission_classes = [permissions.IsAuthenticated]
    serializer_class = UserProfileSerializer
    queryset = UserProfile.objects.all()

    def get_object(self):
        request = self.request
        object = get_object_or_404(
            UserProfile, pk=self.request.user.userprofile.pk)
        return object

    def put(self, request, *args, **kwargs):
        object = self.get_object()
        data = request.data
        if data.get('profile_pic') is not None:
            image = data.get('profile_pic')
            UserProfile.change_profile_pic(object, image)
            return Response("Profile Picture has been changed", status=status.HTTP_200_OK)
        else:
            object.set_default_profile_pic()
            return Response("Profile picture has been set to default", status=status.HTTP_200_OK)
        return super().get(request, *args, **kwargs)


class UserChangePasswordAPIView(APIView):
    permission_classes = [permissions.IsAuthenticated]
    serializer_class = ChangePasswordSerializer

    def get_object(self, queryset=None):
        object = self.request.user
        return object

    def put(self, request, *args, **kwargs):
        serializer = ChangePasswordSerializer(data=request.data)
        self.object = self.get_object()

        if serializer.is_valid():
            data = serializer.data
            if not self.object.check_password(data.get("current_password")):
                return Response({"current_password": ["Wrong password."]}, status=status.HTTP_400_BAD_REQUEST)
            pw = data.get("new_password")
            pw2 = data.get("new_password2")
            if pw != pw2:
                return Response("passwords must match", status=status.HTTP_400_BAD_REQUEST)
            self.object.set_password(data.get("new_password"))
            self.object.save()
            return Response("Password has been changed", status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


# class RegisterAPIView(APIView):
#
#     permission_classes = [permissions.AllowAny]
#     def post(self, request, *args, **kwargs):
#         if request.user.is_authenticated:
#             return Response({'detail': "You are already authenticated"}, status=400)
#         data = request.data
#         username = data.get('username')
#         email = data.get('email')
#         password = data.get('password')
#         password2 = data.get('password2')
#
#
#         qs = User.objects.filter(
#                 Q(username__iexact=username) |
#                 Q(email__iexact=username)
#                 )
#
#
#
#         if password != password2:
#             return Response({"detail":"password must match"}, status=401)
#         if qs.exists():
#             return Response({"detail":"this user already exists"}, status=401)
#         else:
#             user = User.objects.create(username=username, email=email)
#             user.set_password(password)
#             user.save()
#             payload = jwt_payload_handler(user)
#             token = jwt_encode_handler(payload)
#             response = jwt_response_payload_handler(token, user, request=request)
#             return Response(response,status = 201)
#
#         return Response({"detail":"Invalid request"}, status=401)
#


class AuthAPIView(APIView):

    permission_classes = [permissions.AllowAny]

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return Response({'detail': "You are already authenticated"}, status=400)
        data = request.data
        username = data.get('username')
        password = data.get('password')

        user = authenticate(username=username, password=password)
        qs = User.objects.filter(
            Q(username__iexact=username) |
            Q(email__iexact=username)
        ).distinct()

        if qs.count() == 1:
            user_obj = qs.first()
            if user_obj.check_password(password):
                user = user_obj
                payload = jwt_payload_handler(user)
                token = jwt_encode_handler(payload)
                response = jwt_response_payload_handler(
                    token, user, request=request)
                return Response(response)
        return Response({"detail": "Invalid credentials"}, status=401)

crm/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block body_block %}
<div class="site-header">
  <div class="site-header__left">


    <span class="site-header__title">
      Change Password
    </span>
  </div>
  <div class="site-header__right">
    <span class="site-header__breadcrumb">
    <div class="breadcrumbs">
    <a href="{% url 'news:news_list' %}">Home</a>
    &rsaquo;
    <a href="{% url 'accounts:profile' %}">Profile</a>
     &rsaquo; <span>Password Change</span>
    </div>
</span>
  </div>
</div>


<div class="form-container">
<form method="POST" class="post-form">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="save btn btn-default">Save</button>
</form>
</div>
{% endblock %}

crm/accounts/templates/accounts/editprofile.html
{% extends 'base.html' %}
{% block body_block %}
<div class="site-header">
  <div class="site-header__left">


    <span class="site-header__title">
      Change Profile Picture
    </span>
  </div>
  <div class="site-header__right">
    <span class="site-header__breadcrumb">
    <div class="breadcrumbs">
    <a href="{% url 'news:news_list' %}">Home</a>
    &rsaquo;
    <a href="{% url 'accounts:profile' %}">Profile</a>
     &rsaquo; <span>Profile Picture Change</span>
    </div>
</span>
  </div>
</div>

<div class="form-container">


<form method="POST" class="post-form" enctype=multipart/form-data>
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="save btn btn-default">Save</button>
</form>
</div>
{% endblock %}

crm/accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load static %}
{% load groupfilter %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>intranet - Sign in</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
  <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
</head>

<body>
  <div class="login">
    <div class="loginlogo ">
      <span>intranet</span>
    </div>

    <h2> Sign in</h2>
    <form action="{% url 'accounts:user_login' %}" method="post">
      {% csrf_token %}
      <label hidden for="username">Username</label>
      <input type="text" name="username" placeholder="Username, email or phone number">
      <label hidden for="password">Password:</label>
      <input type="password" name="password" placeholder="Password">
      <input type="submit" name="" class="doc secondary-hover" value="Sign in">
    </form>
  </div>
</body>

</html>

crm/accounts/templates/accounts/registration.html
{% extends 'base.html' %}
{% block body_block %}
<div class="site-header">
  <div class="site-header__left">


    <span class="site-header__title">
      Change Password
    </span>
  </div>
  <div class="site-header__right">
    <span class="site-header__breadcrumb">
    <div class="breadcrumbs">
    <a href="{% url 'news:news_list' %}">Home</a>
    &rsaquo;
    <a href="{% url 'accounts:profile' %}">Profile</a>
     &rsaquo; <span>Password Change</span>
    </div>
</span>
  </div>
</div>


<div class="form-container">
<form method="POST" class="post-form">
  {% csrf_token %}
  {{ user_form.as_p }}
  {{ profile_form.as_p }}
  <button type="submit" class="save btn btn-default">Save</button>
</form>
</div>
{% endblock %}

crm/accounts/templates/accounts/set_password.html
{% extends 'base.html' %}
{% block body_block %}
<div class="site-header">
  <div class="site-header__left">


    <span class="site-header__title">
      Set A Password
    </span>
  </div>
  <div class="site-header__right">
    <span class="site-header__breadcrumb">
    <div class="breadcrumbs">
    <a href="{% url 'news:news_list' %}">Home</a>
    &rsaquo;
    <a href="{% url 'accounts:profile' %}">Profile</a>
     &rsaquo; <span>Password Change</span>
    </div>
</span>
  </div>
</div>


<div class="form-container">
<form method="POST" class="post-form">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="save btn btn-default">Save</button>
</form>
</div>
{% endblock %}

crm/accounts/templates/accounts/userprofile_detail.html
{% extends 'base.html' %}

{% block body_block %}


<div class="site-header">
  <div class="site-header__left">


    <span class="site-header__title">
      Users
    </span>
    <span class="site-header__subtitle">/ Your profile</span>
  </div>
  <div class="site-header__right">
    <span class="site-header__breadcrumb">

    <div class="breadcrumbs">
    <a href="{% url 'news:news_list' %}">Home</a>
     &rsaquo; <span>{{title}}</span>
    </div>
</span>
  </div>
  </div>

<div class="content-container content-container--paginated">
  <div class="Ccard">
    <div class="Ccard_header">
      <div class="Ccard_title">Your information</div>
    </div>
    <div class="Ccard_body profile-wrapper">

      <div class="profile_divider">
        <p class="profile-title">Profile Picture</p>

        <img class="avatar" src="{{object.profile_pic.url}}" alt="">
        <div>
          <a class="buttonn" href="{% url 'accounts:edit_profile' %}">
            <div class="doc secondary-hover"> CHANGE </div>
          </a>
          {% if object.profile_pic != "profile_pics/default-profile.png" %}
          <a class="buttonn" href="{% url 'accounts:delete_profile_pic' %}">
            <div class="doc secondary-hover"> Delete</div>
          </a>
          {% endif %}

        </div>
      </div>
      <div class="profile_table">


        <table id="profilegrid">

          <tr>
            <td>Name</td>
            <td>{{object.name}} </td>
          </tr>

          <tr>
            <td>Telephone</td>
            <td>{{object.telephone}} </td>

          </tr>
          <tr>
            <td>Email</td>
            <td>{{object.email}} </td>
          </tr>
          <tr>
            <td>Employed on</td>
            <td>{{object.date_of_employement|date:"m.d.y"}}</td>
          </tr>
          <tr>
            <td>Position</td>
            <td>{{object.position}}</td>
          </tr>
          <tr>
            <td>ID</td>
            <td>{{object.employee_id}}</td>
          </tr>
          <tr>
            <td>Departament</td>
            <td>{{object.get_departament_display}}</td>
          </tr>
          <tr>
            <td>Location</td>
            <td>{{object.get_location_display}}</td>
          </tr>

        </table>

      </div>
      <div class="">


        <a class="buttonn" href="{% url 'accounts:change_password' %}">
          <div class="doc secondary-hover">Change Password</div>
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

crm/accounts/templates/accounts/userprofile_list.html
{% extends 'base.html' %}
{% block extra_css %} .nav__link[name="Contact List"] {background-color: #1caf9a; color: white;} {% endblock %}
{% block body_block %}




<div class="site-header">
  <div class="site-header__left">


    <span class="site-header__title">
      Contact List
    </span>
    <span class="site-header__subtitle">/ Directory of employees</span>
  </div>
  <div class="site-header__right">
    <span class="site-header__breadcrumb">

    <div class="breadcrumbs">
    <a href="{% url 'news:news_list' %}">Home</a>
     &rsaquo; <span>{{title}}</span>
    </div>
</span>
  </div>
</div>



<div class="content-container content-container--paginated">



  <div class="Ccard">
    <div class="Ccard_header">
      <div class="Ccard_title">
        List of employees

      </div>

    </div>
    <div class="Ccard_body">
      <div class="searchbar">
        <form action="{% url 'accounts:employees' %}" method="get">
          <input id="searchbar" name="q" type="text" placeholder="Search...">
          <button type="submit" id="search-submit" class="doc fabutton secondary-hover">
            <i class="fas fa-search"></i>
          </button>

        </form>
      </div>

      <div class="knowledge-table">
        <table id="contact-table" class="content-table">
          <tr>
            <th>Photo</th>
            <th>Name</th>
            <th>Contact Number</th>
            <th>Position</th>
            <th>Departament</th>
            <th>location</th>
            <th>Email adress</th>
          </tr>

          {% for each in object_list %}
          <tr>
            <td> <img class="avatar" src="{{each.profile_pic.url}}" alt="Av" /></td>
            <td> {{each.name}}</td>
            <td> <a href="callto:{{each.telephone}}">{{each.telephone}}</a> </td>
            <td>{{each.position}}</td>
            <td> {{each.get_departament_display}}</td>
            <td> {{each.get_location_display}}</td>
            <td><a href="mailto:{{each.email}}">{{each.email}}</a></td>
          </tr>
          {% endfor %}

        </table>
      </div>
    </div>
  </div>
  <div class="pag-wrapper"> {% if is_paginated %}

    <ul class="pagination">
      {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}">
        <li class="secondary-hover">&laquo;</li>
      </a>
      {% else %}
      <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
      <li class="active pagi__number"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
      <a href="?page={{ i }}">
        <li class="secondary-hover">{{ i }}</li>
      </a>
      {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">
        <li class="secondary-hover">&raquo;</li>
      </a>
      {% else %}
      <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>

    {% endif %}
  </div>
</div>
{% endblock %}