crm/crm/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('suggestions/',include('suggestions.urls',namespace="suggestions")),
    path('calendar/',include('calendary.urls',namespace="calendar")),
    path('',include('news.urls',namespace="news")),
    path('polls/',include('polls.urls',namespace="polls")),
    path('accounts/api/',include('accounts.api.urls')),
    path('calendar/api/',include('calendary.api.urls')),
    path('news/api/',include('news.api.urls')),
    path('suggestions/api/',include('suggestions.api.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/news/api/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import KnowledgeListAPIView, DocQuestionListAPIView, \
    UserQuestionCreateAPIView, DocFileCreateAPIView, NewsFileCreateAPIView, \
    NewsViewSet, DocumentFViewSet

app_name = 'news-api'
router = DefaultRouter()
router.register('news', NewsViewSet, basename='news')
router.register('documents', DocumentFViewSet, basename='documents')

urlpatterns = [
    path('', include(router.urls)),
    path('knowledge/', KnowledgeListAPIView.as_view()),
    path('faq/', DocQuestionListAPIView.as_view()),
    path('userquestion/', UserQuestionCreateAPIView.as_view()),
    path('uploaddocfile/', DocFileCreateAPIView.as_view()),
    path('createnewsfile/', NewsFileCreateAPIView.as_view())
]

crm/news/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from news import views
app_name = 'news'

urlpatterns = [
    path('', views.NewsListView.as_view(), name="news_list"),
    path('news/<int:pk>/', views.NewsDetailView.as_view(), name="newsdetail"),
    path('news/unpublished/',
         views.UnpublishedNewsListView.as_view(), name="unpublished"),
    path('knowledge/', views.KnowledgeCategoryListView.as_view(), name="knowledge"),
    path('knowledge/<int:pk>', views.KnowledgeCategoryDetailView.as_view(),
         name="knowledgedetail"),
    path('upload/news', views.post_news, name="post_news"),
    path('upload/doc', views.post_document, name="createdoc"),
    path('upload/file', views.post_file, name="createfile"),
    path('upload/question', views.post_question, name="createquestion"),
    path('upload/userquestion', views.post_userquestion, name="createuserquestion"),
    path('upload/<int:pk>/updatequestion',
         views.UpdateDocQuestionView.as_view(), name="answerfaq"),
    path('upload/<int:pk>/updatenews',
         views.UnpublishedNewsUpdateView.as_view(), name="updatenews"),
    path('news/<int:pk>/publish/', views.publish_news, name="publish_news"),
    path('flagtoggle/', views.flagtoggle, name="flagtoggle"),
    path('markall/', views.markall, name="markall"),
    path('docs/<int:pk>/', views.DocDetailView.as_view(), name="docdetail"),
    path('faq/', views.QuestionListView.as_view(), name="faq"),
    path('faq/pending/', views.UnansweredQuestionListView.as_view(),
         name="pending_faq"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/news/forms.py
from django import forms
from .models import News, NewsFile, DocumentF, DocFile, DocQuestion, UserQuestion
from django.forms import ClearableFileInput


class NewsForm(forms.ModelForm):
    class Meta():
        model = News
        fields = ['title', 'body',
                  'target_location', 'target_departament']

        widgets = {
            'body': forms.Textarea(attrs={'rows': 3,
                                          'cols': 30,
                                          'class': 'editable',
                                          "placeholder": "Title"}),


        }


class NewsFileForm(forms.ModelForm):
    class Meta:
        model = NewsFile
        fields = ['file']
        widgets = {
            'file': ClearableFileInput(attrs={'multiple': True}),
        }


class DocumentFForm(forms.ModelForm):
    class Meta:
        model = DocumentF
        fields = ['title', 'body', 'target_location',
                  'target_departament', 'category']
        widgets = {
            'body': forms.Textarea(attrs={'rows': 3,
                                          'cols': 30,
                                          'class': 'editable',
                                          "placeholder": "Title"}),
        }


class DocFileForm(forms.ModelForm):
    class Meta:
        model = DocFile
        fields = ['title', 'file', 'target_location',
                  'target_departament', 'category']
        widgets = {
            'file': ClearableFileInput(),
        }


class DocQuestionForm(forms.ModelForm):
    class Meta:
        model = DocQuestion
        fields = ['title', 'body', 'answer', 'target_location',
                  'target_departament', 'category']


class DocQuestionUserForm(forms.ModelForm):
    class Meta:
        model = DocQuestion
        fields = ['title', 'body']

        labels = {
            'title': 'Question',
            'body': 'Description(optional)'
        }

crm/news/api/views.py
import json
import copy
from django.contrib.auth import authenticate, get_user_model
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.mixins import UserPassesTestMixin
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import generics, permissions, status, mixins, viewsets
from rest_framework_jwt.settings import api_settings
from rest_framework.parsers import MultiPartParser
from rest_framework.decorators import action
from rest_framework.authentication import SessionAuthentication
from ..models import News, NewsFile, Notification, NotificationReadFlag, \
    KnowledgeCategory, DocumentF, DocFile, DocQuestion, UserQuestion
from .serializers import NewsFileSerializer, FilteredListSerializer,  \
    DocumentFSmallSerializer, DocumentFSerializer, DocFileSerializer, \
    KnowledgeCategorySerializer, DocQuestionSerializer, UserQuestionSerializer, \
    DocFileUploadSerializer, NewsListSerializer, NewsCRUDSerializer
from accounts.models import UserProfile


User = get_user_model()


def is_json(json_data):
    try:
        real_json = json.loads(json_data)
        is_valid = True
    except ValueError:
        is_valid = False
    return is_valid


class CustomDjangoModelPermission(permissions.DjangoModelPermissions):

    def __init__(self):
        self.perms_map = copy.deepcopy(self.perms_map)
        self.perms_map['GET'] = ['%(app_label)s.view_%(model_name)s']


class KnowledgeListAPIView(generics.ListAPIView):
    permission_classes = [permissions.IsAuthenticated,
                          permissions.DjangoModelPermissions,
                          CustomDjangoModelPermission]
    serializer_class = KnowledgeCategorySerializer
    passed_id = None

    def get_queryset(self):
        request = self.request
        passed_id = request.GET.get('id', None) or self.passed_id
        queryset = KnowledgeCategory.objects.all()

        if passed_id is not None:
            queryset = queryset.filter(id=passed_id)

        return queryset


class DocQuestionListAPIView(
        mixins.CreateModelMixin,
        mixins.UpdateModelMixin,
        mixins.DestroyModelMixin,
        generics.ListAPIView):

    permission_classes = [permissions.IsAuthenticated,
                          permissions.DjangoModelPermissions,
                          CustomDjangoModelPermission]
    serializer_class = DocQuestionSerializer

    def get_queryset(self):
        request = self.request
        query = request.GET.get('q', None)
        queryset = DocQuestion.objects.all()
        if self.request.user.groups.filter(name='Managers').exists():
            pass
        else:
            queryset = queryset.exclude(answer=None)

        if query is not None:
            queryset = queryset.filter(Q(title__icontains=query) | Q(
                answer__icontains=query) | Q(body__icontains=query))

        return queryset

    def get_object(self):
        request = self.request
        passed_id = request.GET.get('pk', None)
        queryset = self.get_queryset()
        obj = None
        if passed_id is not None:
            obj = get_object_or_404(queryset, pk=passed_id)
            self.check_object_permissions(request, obj)
        return obj

    def post(self, request, *args, **kwargs):
        if self.request.user.groups.filter(name='Managers').exists():
            return self.create(request, *args, **kwargs)
        else:
            return Response({'detail': 'You do not have permission to perform \
                this action.'}, status=status.HTTP_403_FORBIDDEN)

    def patch(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)


class UserQuestionCreateAPIView(generics.CreateAPIView):
    permission_classes = [permissions.IsAuthenticated,
                          permissions.DjangoModelPermissions,
                          CustomDjangoModelPermission]
    serializer_class = UserQuestionSerializer
    queryset = DocQuestion.objects.all()

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)


class DocFileCreateAPIView(generics.CreateAPIView):
    permission_classes = [permissions.IsAuthenticated,
                          permissions.DjangoModelPermissions]
    serializer_class = DocFileUploadSerializer
    queryset = DocFile.objects.all()

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)


class NewsFileCreateAPIView(generics.CreateAPIView):
    permission_classes = [permissions.IsAuthenticated,
                          permissions.DjangoModelPermissions]
    serializer_class = NewsFileSerializer
    queryset = NewsFile.objects.all()


class DocumentFViewSet(viewsets.ModelViewSet):
    permission_classes = [permissions.IsAuthenticated,
                          permissions.DjangoModelPermissions,
                          CustomDjangoModelPermission]
    serializer_class = DocumentFSerializer
    queryset = DocumentF.objects.all()


class NewsViewSet(viewsets.ModelViewSet):
    permission_classes = [permissions.IsAuthenticated,
                          permissions.DjangoModelPermissions,
                          CustomDjangoModelPermission]
    serializer_classes = {
        'list': NewsListSerializer,
    }
    default_serializer_class = NewsCRUDSerializer
    queryset = News.objects.all()

    def retrieve(self, request, *args, **kwargs):
        user = User.objects.get(username=request.user)
        news = self.get_object()
        if news.published_date != None:
            notification = Notification.objects.get(news=news)
            notificationreadflag = NotificationReadFlag.objects.get(
                user=user, notification=notification)
            notificationreadflag.read = True
            notificationreadflag.save()
        serializer = self.get_serializer(news)
        return Response(serializer.data)

    def get_serializer_class(self):
        return self.serializer_classes.get(self.action,
                                           self.default_serializer_class)

    def get_queryset(self):
        userprofile = self.request.user.userprofile
        qs = News.objects.all()
        if self.request.user.groups.filter(name='Managers').exists():
            pass
        else:
            qs = qs.exclude(
                published_date=None).order_by('-published_date')
            qs = qs.filter(Q(target_location=userprofile.location) | Q(
                target_location='non'))
            qs = qs.filter(Q(target_departament=userprofile.departament) | Q(
                target_departament='non'))
        return qs

    @action(detail=True, methods=['get'])
    def publish(self, request, pk=None):
        obj = News.objects.get(pk=pk)
        obj.publish()
        return Response({'published_date': obj.published_date},
                        status=status.HTTP_200_OK)

crm/news/templates/news/answer.html
{% extends 'base.html' %}
{% block extra_css %}  .nav__link[name="QandA"] {background-color: #1caf9a; color: white;} {% endblock %}
{% block body_block %}
{% load static %}
{% load groupfilter %}

<div class="site-header">
  <div class="site-header__left">


    <span class="site-header__title">
      FAQaa
    </span>
    <span class="site-header__subtitle">/ Frequently asked questions/span>
  </div>
  <div class="site-header__right">
    <span class="site-header__breadcrumb">Home page</span>
  </div>
</div>


<div class="content-container content-container--paginated">

  {% if request.user|has_group:"Admins" %}
  <div class="moderator_bar">


  <a href="{% url 'news:QandA' %}">Questions</a>
  <a href="{% url 'news:unanQandA' %}">unanswered</a>

    </div>
  {% endif %}
  <div class="objecta">

  </div>


<div class="Ccard">
<div class="Ccard_header">
  <div class="Ccard_title">
    Questions to answer
  </div>
</div>
<div class="Ccard_body">


<div class="questions__wrapper">
  {% for question in object_list %}

  <div class="question">
  <div class="question_title ">
    {{question.title}}
  </div>

  <div class="question_answer">
    {{question.body}}
    <a class="buttonn" href="{% url 'news:answerqna' pk=question.pk %}"><div class="doc secondary-hover">

    answer</div></a>
  </div>
    </div>

    {% endfor %}
</div>

</div>
</div>
</div>
<script type="text/javascript">

  // $('.question_answer').toggle();
  //
  // $(document).ready(function(){
  // $(".question_title").click(function(){
  //     $(this).parents('.question').find('.question_answer').toggle();
  //     $(this).toggleClass("question_title--active")
  //   });
  // });
</script>
{% endblock %}

crm/news/templates/news/docquestion_list.html
{% extends 'base.html' %}
{% block extra_css %} .nav__link[name="faq"] {background-color: #1caf9a; color: white;} {% endblock %}
{% block body_block %}
{% load static %}
{% load groupfilter %}

<div class="site-header">
  <div class="site-header__left">


    <span class="site-header__title">
      FAQ
    </span>
    <span class="site-header__subtitle">/ Frequently asked questions </span>
  </div>
  <div class="site-header__right">
    <span class="site-header__breadcrumb">
      <div class="breadcrumbs">
        <a href="{% url 'news:news_list' %}">Home</a>
        &rsaquo; <span>FAQ</span>
      </div>
    </span>
  </div>
</div>


<div class="content-container content-container--paginated">

  {% if request.user|has_group:"Managers" %}
  <div class="moderator_bar">


    <a href="{% url 'news:faq' %}">Questions</a>
    <a href="{% url 'news:pending_faq' %}">unanswered</a>

  </div>
  {% endif %}
  <div class="objecta">

  </div>

  <div class="Ccard">

    <div class="Ccard_header">


      <div class="Ccard_title">

        Categories
      </div>
    </div>
    <div class="Ccard_body">

      <div class="doc_grid">
        <a class="buttonn" href="{% url 'news:faq' %}">
          <div class="doc secondary-hover">All</div>
        </a>
        {% for news in categories %}
        {% if news.questions.all %}
        <a class="buttonn" href="{% url 'news:faq' %}?category={{news.pk}}">
          <div class="doc secondary-hover">{{news.title}} </div>
        </a>

        {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="Ccard">
    <div class="Ccard_header">

      <a class="buttonn" href="{% url 'news:createuserquestion' %}">
        <div class="doc secondary-hover">Ask a Question </div>
      </a>
    </div>
    <div class="Ccard_body">

      <div class="questions__wrapper">
        {% for question in object_list %}

        <div class="question">
          <div class="question_title secondary-hover">
            {{question.title}}
          </div>

          <div class="question_answer">
            {{question.answer}}
          </div>
        </div>

        {% endfor %}
      </div>

    </div>
  </div>
</div>

{% endblock %}

crm/news/templates/news/documentf_detail.html
{% extends 'base.html' %}
{% block extra_css %} .nav__link[name="Documents"] {background-color: #1caf9a; color: white;} {% endblock %}
{% block body_block %}
{% load static %}
{% load groupfilter %}

<div class="site-header">
  <div class="site-header__left">


    <span class="site-header__title">
      {{object.title|truncatechars:40}}
    </span>
    <span class="site-header__subtitle">/ Directory of useful information</span>
  </div>
  <div class="site-header__right">
    <span class="site-header__breadcrumb">
      <div class="breadcrumbs">
        <a href="{% url 'news:news_list' %}">Home</a>
        &rsaquo;
        <a href="{% url 'news:knowledge' %}">Knowledge</a>
        &rsaquo; <span>{{object.title|truncatechars:20}}</span>
      </div>
    </span>
  </div>
</div>


<div class="content-container">







  <div class="Ccard">
    <div class="Ccard_header primary-hover">


      <div class="Ccard_title">
        {{object.title }}
      </div>
      <div class="Ccard_subtitle">

        {{object.created_date}}

      </div>
    </div>
    <div class="Ccard_body">

      {{object.body|safe}}



    </div>









    {% endblock %}

crm/news/templates/news/knowledgecategory_detail.html
{% extends 'base.html' %}
{% block extra_css %} .nav__link[name="Knowledge"] {background-color: #1caf9a; color: white;} {% endblock %}
{% block body_block %}
{% load static %}
{% load groupfilter %}
<div class="site-header">
  <div class="site-header__left">


    <span class="site-header__title">
      Knowledge - {{object.title}}
    </span>
    <span class="site-header__subtitle">/ Directory of useful information</span>
  </div>
  <div class="site-header__right">
    <span class="site-header__breadcrumb">
      <div class="breadcrumbs">
        <a href="{% url 'news:news_list' %}">Home</a>
        &rsaquo;
        <a href="{% url 'news:knowledge' %}">Knowledge</a>
        &rsaquo; <span>{{object.title}}</span>
      </div>
    </span>
  </div>
</div>
{% if request.user|has_group:"Managers" %}
<div class="moderator_bar">
  <a href="{% url 'news:createfile' %}">Upload file</a>
  <a href="{% url 'news:createdoc' %}">upload a document</a>
</div>
{% endif %}

<div class="content-container">


  <div class="objecta">

  </div>
  <div class="Ccard">

    <div class="Ccard_header">


      <div class="Ccard_title">

        Categories
      </div>
    </div>
    <div class="Ccard_body">
      <div class="doc_grid">
        <a class="buttonn" href="{% url 'news:knowledge' %}">
          <div class="doc secondary-hover">All</div>
        </a>
        {% for cat in categories %}

        <a class="buttonn" href="{% url 'news:knowledgedetail' pk=cat.pk %}">
          <div class="doc secondary-hover">{{cat.title}} </div>
        </a>


        {% endfor %}
      </div>
    </div>
  </div>



  <div class="Ccard">
    <div class="Ccard_body">


      <span class="Ccard_title">Documents</span>
      <div class="knowledge-table">
        <table class="content-table">


          <thead>
            <th>Title</th>
            <th>Category</th>
            <th>Uploaded</th>
          </thead>
          <tbody>

            {% for each in docs %}
            <tr class="tr-hide">
              <td><a href="{{ each.get_absolute_url }}">{{each.title}}</a></td>
              <td>{{each.category}}</td>
              <td>{{each.date_created| date:"d.m.y"}}</td>
            </tr>
            {% endfor %}

            <tr class="moreload">
              <td colspan="3" class="secondary-hover">
                 <span>more +</span></td>
            </tr>

          </tbody>
        </table>
      </div>




      <span class="Ccard_title">Files</span>
      <div class="knowledge-table">

        <table class="content-table">
          <thead>
            <th>Title</th>
            <th>Category</th>

            <th>Size</th>
            <th>Uploaded</th>
          </thead>
          <tbody>
            {% for each in files %}
            <tr class="tr-hide">




              <td> <a href="{{each.file.url}}"> {{each.title}} </a> </td>
              <td>{{each.category}}</td>
              <td>{{each.file.size|sizify}}</td>
              <td>{{each.date_created| date:"d.m.y"}}</td>

            </tr>
            {% endfor %}
            <tr class="moreload">
              <td colspan="4" class="load_more"> <span class="load_more" id="more_files">load more +</span></td>
            </tr>
          </tbody>
        </table>



      </div>
    </div>
  </div>




  {% endblock %}

crm/news/templates/news/knowledgecategory_list.html
{% extends 'base.html' %}
{% block extra_css %} .nav__link[name="Knowledge"] {background-color: #1caf9a; color: white;} {% endblock %}
{% block body_block %}
{% load static %}
{% load groupfilter %}

<div class="site-header">
  <div class="site-header__left">


    <span class="site-header__title">
      Knowledge
    </span>
    <span class="site-header__subtitle">/ Directory of useful information</span>
  </div>
  <div class="site-header__right">
    <span class="site-header__breadcrumb">
      <div class="breadcrumbs">
        <a href="{% url 'news:news_list' %}">Home</a>
        &rsaquo;
        <span>Knowledge</span>

      </div>
    </span>
  </div>
</div>
{% if request.user|has_group:"Managers" %}
<div class="moderator_bar">
  <a href="{% url 'news:createfile' %}">Upload file</a>
  <a href="{% url 'news:createdoc' %}">upload a document</a>
</div>
{% endif %}


<div class="content-container">


  <div class="objecta">

  </div>
  <div class="Ccard">

    <div class="Ccard_header">


      <div class="Ccard_title">

        Categories
      </div>
    </div>
    <div class="Ccard_body">
      <div class="doc_grid">
        <a class="buttonn" href="{% url 'news:knowledge' %}">
          <div class="doc secondary-hover">All</div>
        </a>
        {% for news in object_list %}

        <a class="buttonn" href="{% url 'news:knowledgedetail' pk=news.pk %}">
          <div class="doc secondary-hover">{{news.title}} </div>
        </a>


        {% endfor %}
      </div>
    </div>
  </div>



  <div class="Ccard">
    <div class="Ccard_body">


      <span class="Ccard_title">Documents</span>
      <div class="knowledge-table">
        <table class="content-table">


          <thead>
            <th>Title</th>
            <th>Category</th>
            <th>Uploaded</th>
          </thead>
          <tbody>

            {% for each in docs %}
            <tr class="tr-hide">
              <td><a href="{{ each.get_absolute_url }}">{{each.title}}</a></td>
              <td>{{each.category}}</td>
              <td>{{each.date_created | date:"d.m.y"}}</td>
            </tr>
            {% endfor %}

            <tr class="moreload">
              <td colspan="3" class="secondary-hover"> <span>more +</span></td>
            </tr>

          </tbody>
        </table>
      </div>




      <span class="Ccard_title">Files</span>
      <div class="knowledge-table">

        <table class="content-table">
          <thead>
            <th>Title</th>
            <th>Category</th>

            <th>Size</th>
            <th>Uploaded</th>
          </thead>
          <tbody>
            {% for each in files %}
            <tr class="tr-hide">




              <td> <a href="{{each.file.url}}"> {{each.title}} </a> </td>
              <td>{{each.category}}</td>
              <td>{{each.file.size|sizify}}</td>
              <td>{{each.date_created| date:"d.m.y"}}</td>

            </tr>
            {% endfor %}
            <tr class="moreload">
              <td colspan="4" class="load_more"> <span class="load_more" id="more_files">load more +</span></td>
            </tr>
          </tbody>
        </table>



      </div>
    </div>
  </div>



  {% endblock %}

crm/news/templates/news/news_list.html
{% extends 'base.html' %}
{% block extra_css %} .nav__link[name="Home"] {background-color: #1caf9a; color: white;} {% endblock %}
{% block body_block %}
{% load static %}
{% load groupfilter %}


<div class="site-header">
  <div class="site-header__left">


    <span class="site-header__title">
      Home
    </span>
    <span class="site-header__subtitle">/ Company News</span>
  </div>

</div>
{% if request.user|has_group:"Managers" %}
<div class="moderator_bar">
  <a href="{% url 'news:post_news' %}">Upload a new one</a>
  <a href="{% url 'news:unpublished' %}">unpublished</a>
  <a href="{% url 'news:news_list' %}">published</a>
</div>
{% endif %}

<div class="content-container content-container--paginated">




  <div class="objecta">

  </div>
  <select value="change edition" name="discard_reason" class="MySelect">
    <option value="">--Select--</option>
    <option value="Change edition">Change edition</option>
    <option value="Change to eTextbook">Change to eTextbook</option>
    <option value="Change title">Change title</option>
    <option value="No material required">No material required</option>
  </select>
  {% for news in object_list %}





  <div class="Ccard">
    <div class="Ccard_header primary-hover">


      <div class="Ccard_title">
        {{news.title }}

      </div>
      <div class="Ccard_subtitle">
        {% if news.published_date %}
        {{news.published_date}}
        {% endif %}
      </div>
    </div>
    <div class="Ccard_body">
      {% if not news.published_date %}


      <a class="buttonn" href="{% url 'news:publish_news' pk=news.pk %}">
        <div class="doc secondary-hover">Publish </div>
      </a>
      <a class="buttonn" href="{% url 'news:updatenews' pk=news.pk %}">
        <div class="doc secondary-hover">Update </div>
      </a>
      {% endif %}
      {{news.body | safe}}

      {% if news.files.all %}
      <div class="Ccard_divider">
        Attached files
      </div>
      {% endif %}
      <div class="Ccard_file-container">

        {% for each in news.files.all %}

        <div class="Ccard_file">
          {% if each.extension == 'image' %}
          <img src="{{each.miniature}}">
          <p><a href="{{each.file.get_absolute_url}}" download>Download</a></p>

          {% elif each.extension == 'pdf' %}
          <img src="{% static 'media/pdf-icon.png' %}">
          <p><a href="{{each.file.get_absolute_url}}" download>{{each}}</a></p>
          {% endif %}
        </div>
        {% endfor %}
      </div>


    </div>

  </div>{% endfor %} <div class="pag-wrapper"> {% if is_paginated %}



    <ul class="pagination">
      {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}">
        <li class="secondary-hover">&laquo;</li>
      </a>
      {% else %}
      <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
      <li class="active pagi__number"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
      <a href="?page={{ i }}">
        <li class="secondary-hover">{{ i }}</li>
      </a>
      {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">
        <li class="secondary-hover">&raquo;</li>
      </a>
      {% else %}
      <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>

    {% endif %}
  </div>
</div>{% if object_list.count <= 7 %}
<div class="site-filler">

</div>
{% endif %}

<script>
  $('.Ccard_body').toggle();



  $(document).ready(function() {
    $(".Ccard_header").click(function() {
      $(this).parents('.Ccard').find('.Ccard_body').toggle();

    });
  });
</script>

<script>




</script>
{% endblock %}

crm/news/templates/news/pending_questions.html
{% extends 'base.html' %}
{% block extra_css %} .nav__link[name="faq"] {background-color: #1caf9a; color: white;} {% endblock %}
{% block body_block %}
{% load static %}
{% load groupfilter %}

<div class="site-header">
  <div class="site-header__left">


    <span class="site-header__title">
      Pending Questions
    </span>
    <span class="site-header__subtitle">/ Frequently asked questions</span>
  </div>
  <div class="site-header__right">
    <span class="site-header__breadcrumb">
      <div class="breadcrumbs">
        <a href="{% url 'news:news_list' %}">Home</a>
        &rsaquo;
        <span>Pending Questions</span>

      </div>
    </span>
  </div>
</div>


<div class="content-container content-container--paginated">

  {% if request.user|has_group:"Managers" %}
  <div class="moderator_bar">


    <a href="{% url 'news:faq' %}">Questions</a>
    <a href="{% url 'news:pending_faq' %}">unanswered</a>

  </div>
  {% endif %}
  <div class="objecta">

  </div>


  <div class="Ccard">
    <div class="Ccard_header">
      <div class="Ccard_title">
        Questions to answer
      </div>
    </div>
    <div class="Ccard_body">


      <div class="questions__wrapper">
        {% for question in object_list %}

        <div class="question">
          <div class="question_title ">
            {{question.title}}
          </div>

          <div class="question_answer">
            {{question.body}}

            <a class="buttonn" href="{% url 'news:answerfaq' pk=question.pk %}">
              <div class="doc secondary-hover">

                answer</div>
            </a>
          </div>
        </div>

        {% endfor %}
      </div>

    </div>
  </div>
</div>

{% endblock %}

crm/news/templates/news/upload.html
{% extends 'base.html' %}

{% block extra_css %} .nav__link[name="Home"] {background-color: #1caf9a; color: white;} {% endblock %}

{% block body_block %}
<div class="site-header">
  <div class="site-header__left">


    <span class="site-header__title">
      Submit
    </span>
  </div>
  <div class="site-header__right">
    <span class="site-header__breadcrumb">
      <div class="breadcrumbs">
        <a href="{% url 'news:news_list' %}">Home</a>

      </div>
    </span>
  </div>
</div>
<div class="form-container">


  <form method="POST" class="post-form" enctype="multipart/form-data">

    {% csrf_token %}

    {{ form.as_p}}
    {{ file_form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
  </form>
</div>

{% endblock %}