crm/crm/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('suggestions/',include('suggestions.urls',namespace="suggestions")),
    path('calendar/',include('calendary.urls',namespace="calendar")),
    path('',include('news.urls',namespace="news")),
    path('polls/',include('polls.urls',namespace="polls")),
    path('accounts/api/',include('accounts.api.urls')),
    path('calendar/api/',include('calendary.api.urls')),
    path('news/api/',include('news.api.urls')),
    path('suggestions/api/',include('suggestions.api.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/news/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from news import views
app_name = 'news'

urlpatterns = [
    path('', views.NewsListView.as_view(), name="news_list"),
    path('news/<int:pk>/', views.NewsDetailView.as_view(), name="newsdetail"),
    path('news/unpublished/',
         views.UnpublishedNewsListView.as_view(), name="unpublished"),
    path('knowledge/', views.KnowledgeCategoryListView.as_view(), name="knowledge"),
    path('knowledge/<int:pk>', views.KnowledgeCategoryDetailView.as_view(),
         name="knowledgedetail"),
    path('upload/news', views.post_news, name="post_news"),
    path('upload/doc', views.post_document, name="createdoc"),
    path('upload/file', views.post_file, name="createfile"),
    path('upload/question', views.post_question, name="createquestion"),
    path('upload/userquestion', views.post_userquestion, name="createuserquestion"),
    path('upload/<int:pk>/updatequestion',
         views.UpdateDocQuestionView.as_view(), name="answerfaq"),
    path('upload/<int:pk>/updatenews',
         views.UnpublishedNewsUpdateView.as_view(), name="updatenews"),
    path('news/<int:pk>/publish/', views.publish_news, name="publish_news"),
    path('flagtoggle/', views.flagtoggle, name="flagtoggle"),
    path('markall/', views.markall, name="markall"),
    path('docs/<int:pk>/', views.DocDetailView.as_view(), name="docdetail"),
    path('faq/', views.QuestionListView.as_view(), name="faq"),
    path('faq/pending/', views.UnansweredQuestionListView.as_view(),
         name="pending_faq"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/polls/urls.py
from django.urls import path
from . import views
app_name = 'polls'
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # path('employees/',views.EmployeeListView.as_view(),name="employees"),
    path('',views.PollListView.as_view(),name="poll_list"),
    path('unpublished/',views.UnpublishedPollListView.as_view(),name="unpublishedpolllist"),
    path('<int:pk>/',views.create_poll_answer,name="create_poll_answer"),
    path('add/',views.post_Poll,name="pollform"),
    path('add/<int:pk>/',views.create_poll_question,name="create_poll_question"),
    path('publish/<int:pk>/',views.publishpoll,name="publishpoll"),
    path('submitions/',views.PollListAnswerView.as_view(),name="poll_submitions"),
    path('submitions/<int:pk>',views.PollAnswerDetailView.as_view(),name="detailanswers")

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/polls/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from accounts.choices.choices import *
from django.template.defaultfilters import slugify

class Poll(models.Model):
    date_created = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey('auth.User', on_delete=models.PROTECT)
    title = models.CharField(max_length=200)
    published_date = models.DateTimeField(default=None, null=True, blank=True)
    target_departament = models.CharField(
        max_length=3, choices=DEPARTAMENTS, default='non')
    target_location = models.CharField(
        max_length=3, choices=COMPANY_LOCATIONS, default='non')
    slug = models.SlugField(max_length=20,null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('polls:create_poll_answer', args=[str(self.id)])

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title[0:20])
        super(Poll, self).save(*args, **kwargs)


class Question(models.Model):
    poll = models.ForeignKey('polls.Poll', on_delete=models.CASCADE,
                             null=True, blank=True, related_name='questions')
    title = models.CharField(max_length=200)
    order = models.IntegerField(null=True, blank=True)
    enabletext = models.BooleanField(default=False)
    type = models.CharField(max_length=3, choices=QUESTIONTYPES, default='chc')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['order']


class Answer(models.Model):
    body = models.TextField(max_length=200)
    question = models.ForeignKey(
        'polls.Question', on_delete=models.CASCADE, related_name='answers')

    def __str__(self):
        return self.body


class PollSubmition(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    poll = models.ForeignKey(
        'polls.Poll', on_delete=models.CASCADE, related_name='submitions')
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.user.username + " " + self.poll.title)


class PollSubmitionQuestion(models.Model):
    submition = models.ForeignKey(
        'polls.PollSubmition', on_delete=models.CASCADE, related_name='submitions')
    question = models.ForeignKey(
        'polls.Question', on_delete=models.CASCADE, related_name='submitions')
    manyanswer = models.ManyToManyField(
        'polls.Answer', related_name='submitions', blank=True)
    answer = models.TextField(max_length=200, null=True, blank=True)
    text = models.TextField(max_length=200, null=True, blank=True)
    date = models.DateField(null=True, blank=True)
    order = models.IntegerField(null=True, blank=True)

    def ans(self):
        if self.answer != None and self.text == None:

            return str(self.answer)
        elif self.answer != None and self.text is not None:
            return str(self.answer + "; " + self.text)
        elif self.text is not None:
            return str(self.text)
        elif self.date:
            return self.date.strftime("%m/%d/%Y")

    def __str__(self):
        return str(self.ans())

crm/polls/forms.py
from django import forms
from .models import Poll

class PollForm(forms.ModelForm):
    class Meta():
        model = Poll
        fields = ['title','target_departament','target_location']

crm/polls/views.py

from django.shortcuts import render, get_object_or_404, redirect
from .forms import PollForm
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import ListView, DetailView
from .models import Poll, Question, Answer, PollSubmition, PollSubmitionQuestion
from django.utils import timezone
from django.contrib import messages
import json
from django.http import JsonResponse
from django.contrib.auth.decorators import permission_required


class PollListAnswerView(PermissionRequiredMixin,
                            LoginRequiredMixin,
                            ListView):
    model = Poll
    template_name = 'polls/poll_record_list.html'
    permission_required = 'polls.view_pollsubmition'
    def get_queryset(self):
        queryset = Poll.objects.exclude(
            published_date=None).order_by('-published_date')
        return queryset

class PollAnswerDetailView(PermissionRequiredMixin,
                            LoginRequiredMixin,
                            DetailView):
    model = Poll
    template_name = 'polls/poll_record_detail.html'
    permission_required = 'polls.view_pollsubmition'


class PollListView(LoginRequiredMixin, ListView):
    def get_queryset(self):

        queryset = Poll.objects.exclude(
            published_date__lt = self.request.user.date_joined).exclude(
            published_date=None).order_by('-published_date')
        submitions_set = PollSubmition.objects.filter(
            user=self.request.user).exclude(submitions__isnull=True)
        queryset = queryset.exclude(submitions__in=submitions_set)

        return queryset


class UnpublishedPollListView(PermissionRequiredMixin,
                                LoginRequiredMixin,
                                ListView):
    permission_required = 'polls.view_pollsubmition'

    def get_queryset(self):
        return Poll.objects.filter(published_date=None).order_by('-date_created')


@login_required
@permission_required('calendary.add_poll', raise_exception=True)
def post_Poll(request):
    if request.method == 'POST':
        form = PollForm(request.POST)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = User.objects.get(username=request.user.username)
            instance.save()
            return redirect('polls:create_poll_question', pk=instance.pk)
    else:
        form = PollForm()
    return render(request, 'polls/pollform.html', {'form': form})


@login_required
@permission_required('calendary.edit_poll', raise_exception=True)
def publishpoll(request, pk):
    poll = get_object_or_404(Poll, pk=pk)
    poll.publish()
    return redirect('polls:poll_list')


# executed for every added question
@login_required
@permission_required('polls.edit_poll', raise_exception=True)
def create_poll_question(request, pk):
    poll = get_object_or_404(Poll, pk=pk)
    context = {}
    if poll.published_date == None:
        if request.is_ajax() and request.method == 'POST':
            json_body = json.loads(request.body)
            print(json_body)
            title = json_body.get('title')
            enabletext = json_body.get('enabletext')
            type = json_body.get('type')
            answer_list = json_body.get('answers')
            order = json_body.get('order')
            instance = Question.objects.create(
                poll=poll,
                title=title,
                enabletext=enabletext,  # swapname
                type=type,
                order=order
            )
            if instance.type != "txt":
                for each in answer_list:
                    Answer.objects.create(
                        body=each,
                        question=instance
                    )
            return HttpResponse("OK")
        else:

            context = {"data": poll}
                       # "questions": Question.objects.all()}
            return render(request, 'polls/create_poll_question.html', context)
    else:
        return redirect('polls:poll_list')


# executed for every question in a poll
@login_required
def create_poll_answer(request, pk):
    poll = get_object_or_404(Poll, pk=pk)
    currentuser = request.user
    context = {}
    if request.is_ajax() and request.method == 'POST':
        submition = PollSubmition.objects.get(user=currentuser, poll=poll)
        question_pk = json.loads(request.body).get('question')
        questionobj = Question.objects.get(pk=question_pk)
        answer_list = json.loads(request.body).get('answer',None)
        text = json.loads(request.body).get('text',None)
        date = json.loads(request.body).get('date')

        if len(answer_list) > 0:
            answerstr = str(" ")
            for counter, each in enumerate(answer_list):
                if counter > 0:
                    answerstr = answerstr + ";"
                answerstr = answerstr + str(Answer.objects.get(pk=each).body)

            answer_instance = PollSubmitionQuestion.objects.create(
                submition=submition,
                question=questionobj,
                order=questionobj.order,
                answer=answerstr,
                date=date,
                text=text,
            )
            for each in answer_list:
                answer_instance.manyanswer.add(each)

        else:
            answer_instance = PollSubmitionQuestion.objects.create(
                submition=submition,
                question=questionobj,
                order=questionobj.order,
                text=text,
                date=date,
            )
        submition.save()
        return HttpResponse("OK")
    else:
        submition, created = PollSubmition.objects.get_or_create(
            poll=poll,
            user=currentuser,
        )
        if submition.submitions.exists():

            return redirect('polls:poll_list')

        else:

            context["poll"] = Poll.objects.get(pk=pk)
            return render(request, 'polls/poll_detail.html', context)

crm/polls/templates/polls/create_poll_question.html
{% extends 'base.html' %}

{% block body_block %}
{% load static %}



<div class="site-header">
  <div class="site-header__left">


    <span class="site-header__title">
      {{data.title}}
    </span>
    <span class="site-header__subtitle">/ Add poll questions</span>
  </div>
  <div class="site-header__right">
    <span class="site-header__breadcrumb">
    <div class="breadcrumbs">
    <a href="{% url 'news:news_list' %}">Home</a>
     &rsaquo;
     <a href="{% url 'polls:poll_list' %}">Polls</a>
     &rsaquo; <span>{{data.title}}</span>
    </div>
</span>
  </div>
</div>

<div class="form-container">


<form id="form" method="POST" class="pollcreation">
  {% csrf_token %}
  <div class="question">
    <input class="title comment-input" placeholder="Your Question" id="last_name" type="text" name="lang">




    <p> <input type="checkbox" class="enable" name="enable text" value=""></p>
    <p>type of answers?</p>
    <select name="0" class="select">
    <p><label><option name="0" value="mch"> Multiple Choice</label></p>
    <p> <label><option  name="0"value="chc"> radio</label></p>
    <p> <label><option  name="0" value="txt"> text</label></p>
    <p> <label><option  name="0" value="pck"> list</label></p>
    <p> <label><option  name="0" value="dat"> date</label></p>
    </select>
    <p>possible answer</p>
    <div class="answers">
      <p><input class="answer comment-input" type="text" name="lang"></p>

      <p><input class="answer comment-input" type="text" name="lang"></p>

    </div>
    <p><button type="button" class="addanswer" name="button">add another answer</button></p>



    <p><button type="button" name="button" class="addquestion">add another question</button></p>
    <!-- <p><button type="button" name="button" class="removequestion">remove this question</button></p> -->

  </div>


      <input data-id="{{data.pk}}" data-href="{% url 'polls:create_poll_question' pk=data.pk %}" type="submit" name="submit" value="submit" class="form-button comment-submit">
</form>

</div>


<script type="text/javascript">
var n = 1


$(document).ready(function(){
  $.ajaxSetup({
       beforeSend: function(xhr, settings) {
           function getCookie(name) {
               var cookieValue = null;
               if (document.cookie && document.cookie != '') {
                   var cookies = document.cookie.split(';');
                   for (var i = 0; i < cookies.length; i++) {
                       var cookie = jQuery.trim(cookies[i]);
                       // Does this cookie string begin with the name we want?
                       if (cookie.substring(0, name.length + 1) == (name + '=')) {
                           cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                           break;
                       }
                   }
               }
               return cookieValue;
           }
           if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
               // Only send the token to relative URLs i.e. locally.
               xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
           }
       }
  });

});


  $(document).on('click',".addanswer",function (e) {

            $(this).parents(".question").find(".answers").append(
            '<div class="answerwrapper">'+

            '<p><input class="answer comment-input" type="text" name="lang">'+
            '<button type="button" class="removeanswer">remove this answer</button></p></div>'
            );
          });




$(document).on('change',"select[class=select]",function (e) {

      if($(this).val() == "txt" || $(this).val() == "dat"){

              $(this).parents('.question').find('.answer').attr("disabled","disabled");
              $(this).parents('.question').find('.answer').prop("value","");
              $(this).parents('.question').find('.addanswer').attr("disabled","disabled");
              $(this).parents('.question').find('.enable').attr("disabled","disabled");
              $(this).parents('.question').find('.enable').prop('checked', false);
      }
      else if($(this).val() == "pck"){
              $(this).parents('.question').find('.enable').attr("disabled","disabled");
              $(this).parents('.question').find('.enable').prop('checked', false);

              $(this).parents('.question').find('.answer').removeAttr("disabled","disabled");
              $(this).parents('.question').find('.addanswer').removeAttr("disabled","disabled");

      }

      else{
        $(this).parents('.question').find('.answer').removeAttr("disabled","disabled");
        $(this).parents('.question').find('.addanswer').removeAttr("disabled","disabled");
        $(this).parents('.question').find('.enable').removeAttr("disabled","disabled");
      }
        });


// $(document).on('click',"input[type=radio]",function (e) {
//       if($(this).val() == "pck"){
//               $(this).parents('.question').find('.enable').attr("disabled","disabled");
//               $(this).parents('.question').find('.enable').prop('checked', false);
//
//       }
//       else{
//         $(this).parents('.question').find('.enable').removeAttr("disabled","disabled");
//       }
//         });
//


$(document).on('click',".removequestion",function (e) {

          $(this).parents('.question')[0].remove();
        });


$(document).on('click',".removeanswer",function (e) {

          $(this).parents('.answerwrapper')[0].remove();
        });



        $(document).on('click',".addquestion",function (e) {

          $(
          '<div class="question">'+
            '<input class="title comment-input" placeholder="Your Question" id="last_name" type="text" name="lang">'+


            '<p> <input type="checkbox" class="enable" name="enable text" value=""></p>'+
            '<p>type of answers?</p>'+
              '<select name="'+n+'" class="select">'+
            '<p><label><option value="mch"> Multiple Choice</label></p>'+
            '<p> <label><option  value="chc"> radio</label></p>'+
            '<p> <label><option   value="txt"> text</label></p>'+
            '<p> <label><option  value="pck"> list</label></p>'+
            '<p> <label><option   value="dat"> Date</label></p>'+
            '</select>'+
            '<p>possible answer</p>'+
            '<div class="answers">'+
              '<p><input class="answer comment-input" type="text" name="lang"></p>'+

              '<p><input class="answer comment-input" type="text" name="lang"></p>'+

            '</div>'+
          '  <p><button type="button" class="addanswer" name="button">add another answer</button></p>'+



          '  <p><button type="button" name="button" class="addquestion">add another question</button></p>'+
      '      <p><button type="button" name="button" class="removequestion">remove this question</button></p>'+

          '</div>'

        ).insertAfter($('.question').last());
        n = n + 1;
        });


  $(document).on('click','.comment-submit',function (e) {
    var csrftoken = $("input[name=csrfmiddlewaretoken]").val();
    e.preventDefault();
    var pk = $(this).data("pk");
    var urlss = $(this).attr("data-href");

    $('.question').each(function(i,e) {

      var ans = [];
      $(this).find('.answer').each(function(i,e){
        ans.push($(this).val());
      });
      console.log($(this).find(".title").val());
      console.log($(this).find(".enable").is(':checked'));
      console.log(ans);
      console.log($(this).find("input[name='"+i+"']:checked").prop("name"));

      // console.log($(this).find("input[name='type"+i+"']:checked").val());
      $.ajax({
          type:'POST',
          url: urlss,
          data:JSON.stringify({

              "title":$(this).find('.title').val(),
              "enabletext":$(this).find('.enable').is(':checked'),
              "type":$(this).find('select[name="'+i+'"]').val(),
              "answers":ans,
              "order":$(this).find('select[name="'+i+'"]').prop("name"),
              "pk": pk,
              // "csrfmiddlewaretoken": csrftoken,
              // "action": 'post'
          }),

          success:(json) => {
            console.log('yaaay');
                // window.location.href = '{% url 'polls:poll_list' %}';

          },
          error : function(xhr,errmsg,err) {
          console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
      }
      });
     });

});


// $(document).on('click','.importquestion',function (e) {
//   // var csrftoken = $("input[name=csrfmiddlewaretoken]").val();
//   e.preventDefault();
//   var pk = $(this).parent().parent().find(".select").val();
//   var urlss = $(this).attr("data-href");
//   console.log(pk);
//   console.log(urlss);
//     // console.log($(this).find("input[name='type"+i+"']:checked").val());
//     $.ajax({
//         type:'POST',
//         url: urlss,
//         // datatype: 'json',
//         data:JSON.stringify({
//             "pk": pk,
//             // "csrfmiddlewaretoken": csrftoken,
//             // "action": 'post'
//         }),
//
//         success:(json) => {
//           console.log(json);
//
//
//         },
//         error : function(xhr,errmsg,err) {
//         console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
//     }
//     });
//    });
//




</script>


{% endblock %}

crm/polls/templates/polls/poll_list.html
{% extends 'base.html' %}
{% block extra_css %} .nav__link[name="Polls"] {background-color: #1caf9a; color: white;} {% endblock %}
{% block body_block %}
{% load static %}
{% load groupfilter %}
<div class="site-header">
  <div class="site-header__left">


    <span class="site-header__title">
      Polls
    </span>
    <span class="site-header__subtitle">/ Polling station</span>
  </div>
  <div class="site-header__right">
    <span class="site-header__breadcrumb">
    <div class="breadcrumbs">
    <a href="{% url 'news:news_list' %}">Home</a>
     &rsaquo;
 <span>Polls</span>

    </div>
</span>
  </div>
</div>




<div class="content-container ">
  {% if request.user|has_group:"Managers" %}
  <div class="moderator_bar">
    <a href="{% url 'polls:poll_list' %}">Published polls</a>
    <a href="{% url 'polls:unpublishedpolllist' %}">Unpublished polls</a>
    <a href="{% url 'polls:pollform' %}">Create a poll</a>
    <a href="{% url 'polls:poll_submitions' %}">Submitions</a>
  </div>
  {% endif %}








  <div class="Ccard">
    <div class="Ccard_header">
      <div class="Ccard_title">
        Your polls
      </div>
    </div>
    <div class="Ccard_body">

      <div class="questions__wrapper">

        {% for poll in object_list %}
        <div class="question">
          <a class="buttonn" href="{{ poll.get_absolute_url }}" style="display:block;">
            <div class="question_title secondary-hover">
              {{poll.title}}
              <span class="Ccard_subtitle">{{poll.published_date|date:"m.d.y"}}</span>
            </div>
          </a>
          {% if poll.published_date is None %}
          <a href="{% url 'polls:publishpoll' pk=poll.pk %}">publish</a>
          {% endif %}
        </div>


        {% endfor %}
      </div>

    </div>
  </div>
</div>


{% endblock %}

crm/polls/templates/polls/poll_record_detail.html
{% extends 'base.html' %}
{% block extra_css %}  .nav__link[name="Polls"] {background-color: #1caf9a; color: white;} {% endblock %}
{% block body_block %}
{% load static %}
{% load groupfilter %}



  <div class="site-header">
    <div class="site-header__left">


      <span class="site-header__title">
          {{object.title}} - Results
      </span>
      <span class="site-header__subtitle">/ Polling station</span>
    </div>
    <div class="site-header__right">
      <span class="site-header__breadcrumb">
      <div class="breadcrumbs">
      <a href="{% url 'news:news_list' %}">Home</a>
&rsaquo;  <a href="{% url 'polls:poll_submitions' %}">Poll results</a>
       &rsaquo; <span>{{object.title}}</span>
      </div>
  </span>
    </div>
  </div>



<div class="content-container">

  <div class="Ccard">

  <div class="Ccard_header">


  <div class="Ccard_title">

{{object.title}}
</div>
</div>
<div class="Ccard_body">


  <div class="knowledge-table">
<table>
  <thead>


  <th>User</th>
  {% for each in object.questions.all|dictsort:'order'  %}
  <th>{{each.title}}</th>
  {% endfor %}
    </thead>
  <tbody>
    {% for e in object.submitions.all %}
    <tr>
      <td>{{e.user.userprofile.name}}</td>
      {% for r in e.submitions.all|dictsort:'order' %}
    <td> {{r.ans}}</td>
      {% endfor %}
    </tr>
{% endfor %}
  </tbody>
</table>

</div></div>

</div>

    </div>




  {% endblock %}

crm/polls/templates/polls/poll_record_list.html
{% extends 'base.html' %}
{% block extra_css %}  .nav__link[name="Polls"] {background-color: #1caf9a; color: white;} {% endblock %}
{% block body_block %}
{% load static %}
{% load groupfilter %}
<div class="site-header">
  <div class="site-header__left">


    <span class="site-header__title">
      Poll Results
    </span>

  </div>
  <div class="site-header__right">
    <span class="site-header__breadcrumb">
    <div class="breadcrumbs">
    <a href="{% url 'news:news_list' %}">Home</a>

     &rsaquo; <span>Poll results</span>
    </div>
</span>
  </div>
</div>


<div class="content-container content-container--paginated">
  {% if request.user|has_group:"Managers" %}
  <div class="moderator_bar">



    </div>
  {% endif %}
<div class="Ccard">
  <div class="Ccard_header">


  <div class="Ccard_title">
    List of Polls
      </div>
  </div>

<div class="Ccard_body">



  {% for poll in object_list %}

  <div class="question">
        <a class="buttonn" href="{% url 'polls:detailanswers' pk=poll.pk %}" style="display:block;"><div class="question_title secondary-hover">
    {{poll.title}}
    <span class="Ccard_subtitle">{{poll.published_date|date:"m.d.y"}}</span>
        <span class="Ccard_subtitle">Submitions: {{poll.submitions.count}}</span></div>
</a>

</div>
          {% endfor %}


    </div>




  {% endblock %}

crm/polls/templates/polls/pollform.html
{% extends 'base.html' %}

{% block body_block %}

<div class="site-header">
  <div class="site-header__left">


    <span class="site-header__title">
      Initiate a poll
    </span>

  </div>
  <div class="site-header__right">
    <span class="site-header__breadcrumb">
    <div class="breadcrumbs">
    <a href="{% url 'news:news_list' %}">Home</a>

     &rsaquo; <span>Poll initiation</span>
    </div>
</span>
  </div>
</div>
<div class="form-container">


<form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
</form>
</div>
{% endblock %}